### ISSUE TITLE
Jupterquiz in Jupyterlite notebook

### ISSUE THREAD

**Issue by hyanwong** [jmshea/jupyterquiz#12]
I'm running a workshop in which students run [JupyterLite](https://jupyterlite.readthedocs.io/en/latest/) inside their browser on their own laptops, which is much more convenient than having to sort out a running JupyterLab environment for them. Doe anyone have any experience of getting jupyterquiz to run within this enviroment? Is it even possible, given that things like `urllib.request` don't work in the jupyterlite sandbox?

**Comment by jmshea** [comment]
Sorry I missed this -- I'll take a look at this use case

**Comment by jmshea** [comment]
At a quick glance, this doesn't look too hard to fix. I'll try to get to it today

**Comment by jmshea** [comment]
OK. It is working for me now with 2.1.0. Please try it and see if it works for you. Here is some example code that works for me on JupyterLite:

```import micropip
await micropip.install('jupyterquiz')

import pkg_resources # I don't understand exactly why this has to be done separately

from jupyterquiz import display_quiz
git_url='https://raw.githubusercontent.com/jmshea/Foundations-of-Data-Science-with-Python/main/questions/'

import jupyterquiz

#Uncomment this line if you have any problems and make sure you are getting 2.1.0
#print(f'Version = {jupyterquiz.__version__}')

display_quiz(git_url+'ch1.json')
```

**Comment by jmshea** [comment]
Update that `import pkg_resources` is not needed any more, and by eliminating dependence on that library (part of `setuptools`), I have sped up loading. Thus, the following should be sufficient

```
import micropip
await micropip.install('jupyterquiz')

from jupyterquiz import display_quiz
git_url='https://raw.githubusercontent.com/jmshea/Foundations-of-Data-Science-with-Python/main/questions/'

display_quiz(git_url+'ch1.json')
```

**Comment by hyanwong** [comment]
Sorry for the slow reply here. This is not working perfectly for me. Thanks so much! Closing.
