### ISSUE TITLE
How to Layout answers horizontally?

### ISSUE THREAD

**Issue by arashash** [jmshea/jupyterquiz#14]
Hii. Thanks for the awesome package. 
Is it possible to change the layout of the answers?
I need to provide a wide range of answers (about ten options), so it would be great if they were spread horizontally instead.

**Comment by arashash** [comment]
THANK YOU SO MUCH. This is how it looks on my side:
![image](https://user-images.githubusercontent.com/15813444/233533611-3242b0ff-c343-4f34-943c-9e60907dac1b.png)

having control over the size would be great too. A fixed button width would be better I think.
Also, it would look awesome if the button texts were centered and had sharp corners. like this: 

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP._0-7_GTSd-R1tR9k8paXhgHaEL%26pid%3DApi&f=1&ipt=12ed5641d9df98b610882bff58c4ca4bb1ced7428058dfcee2d3ab4f13794717&ipo=images" class="img-responsive" alt=""> </div>

**Comment by jmshea** [comment]
OK, can you try it with

`pip install jupyterquiz==2.3.0`

when you call display_quiz, pass the keyword argument `border_radius=0`

**Comment by arashash** [comment]
Looks Awesome. I think it'd be even better if the questions were also centered. Here's my output:
![image](https://user-images.githubusercontent.com/15813444/233649398-2169db91-2f96-4946-b8a1-64895b063bd2.png)

Btw is there a way to control the width right now?

**Comment by jmshea** [comment]
Try with latest version: `pip install jupyterquiz==2.3.5`

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/6517343/233707429-4bf30737-8e4c-4c27-a36a-139be438b947.png">

You will have to be sure to pass the correct options, as in the example.

**Comment by arashash** [comment]
woow it looks perfect. Thaanks
![image](https://user-images.githubusercontent.com/15813444/233710238-6ce4418b-9dc5-45f8-bc57-1242ef4dd6b7.png)

**Comment by jmshea** [comment]
New features added to support requested formatting.
