### ISSUE TITLE
Jupyter polls?

### ISSUE THREAD

**Issue by arashash** [jmshea/jupyterquiz#16]
Have you considered having polls? Something that, when you click on it, shows the distribution. Like Twitter or LinkedIn polls. I think having polls is a great way to hook students on a topic they are hesitant to learn. For example, if they see that the majority of people are thinking wrong about something after seeing the distribution, then they'd be psyched to want to learn to become the minority :) 
I'd be very happy to help with this since we are planning to use it in our newly funded educational project at https://c4r.io/about-us/

**Comment by jmshea** [comment]
Right now, I don't see how this functionality fits in with the core approach of JupyterQuiz, which requires no server and caches questions for use offline. There are no privacy issues, as all responses are kept local to the user's browser. 

Given this context, please let me know what you think.

**Comment by arashash** [comment]
Definitely. I am thinking of an offline poll where the distribution is stored and not updated. This way, instead of showing true or false we could show a distribution of answers (based on an actual poll for example on Twitter). Something like this:
![image](https://user-images.githubusercontent.com/15813444/235780580-67b874fd-0574-45f0-af02-9206ee60ed3c.png)

**Comment by jmshea** [comment]
After some thought, I think this does not fit with the purpose of JupyterQuiz, which is interactive quizzes. Given this, I am planning to close this issue. 

If you disagree, please let me know.

**Comment by arashash** [comment]
I understand. Let me know if you'd be interested in the future. Cheers!
