### ISSUE TITLE
import error in jupyterlite

### ISSUE THREAD

**Issue by djangoliv** [jmshea/jupyterquiz#18]
when I run the sample code on jupyterlab, I get the following error:

```
File /lib/python3.11/site-packages/jupyterquiz/dynamic.py:158, in display_quiz(ref, num, shuffle_questions, shuffle_answers, preserve_responses, border_radius, question_alignment, max_width, colors)
    156 url = ref
    157 if sys.platform == 'emscripten':
--> 158     from pyodide import open_url
    159     text = open_url(url).read()
    160     script+=text

ImportError: cannot import name 'open_url' from 'pyodide' (/lib/python311.zip/pyodide/__init__.py)

import pyodide
```
jupyterlite==0.1.0
jupyterquiz==2.5.2
pyodide==0.23.0

**Comment by jmshea** [comment]
I think I have fixed this in 2.6.1, but it would be great if you could test it. micropip is not yet detecting the wheel file for 2.6.1 for me, so please try either

`await micropip.install('jupyterquiz==2.6.1')`

or if that doesn't work at your testing time, try
`await micropip.install('https://files.pythonhosted.org/packages/5f/d4/3c108c387e19d7c724832e843caeaab4579e902e15565208402f52a3a7fd/jupyterquiz-2.6.1-py2.py3-none-any.whl')
`

and let me know if the error is resolved.

**Comment by djangoliv** [comment]
The results:

`await micropip.install('jupyterquiz==2.6.1')`
return 
`ValueError: Can't find a pure Python 3 wheel for 'jupyterquiz==2.6.1'.`

But your second workaround works.

Thanks

**Comment by jmshea** [comment]
The 2.6.1 wheel is available for me now. Can you restart your kernel and try again with the first command?
