### ISSUE TITLE
Cannot read questions from spans

### ISSUE THREAD

**Issue by PhilippRisius** [jmshea/jupyterquiz#25]
With JupyterLab, it seems no longer possible to read questions from hidden spans in notebook cells. As a consequence, the HideQuiz notebook no longer works. More specifically, `document.getElementById("question1")` yields `null`.

I like that the notebook source itself contains the questions in a non-human-readable format for portability. I tinkered around a bit and found the following solution for finding question sources:

```python
def find_quiz(tag):
    import os
    import nbformat
    from bs4 import BeautifulSoup
    nb_path = os.getenv("JPY_SESSION_NAME")
    with open(nb_path) as f:
        notebook = nbformat.read(f, nbformat.NO_CONVERT)
    markdown_source = 'CELL'.join(
        cell['source']
        for cell in notebook['cells']
        if cell['cell_type'] == 'markdown'
    )
    item = BeautifulSoup(markdown_source).find('span', {'id': tag})

    if item is not None:
        return item.text
    else:
        raise ValueError("Requested Tag was not found")
```

This is also a bit hacky, but perhaps it can serve as a starting point. What do you think?

**Comment by jmshea** [comment]
Thanks for bringing this to my attention. I don't use this feature, so I don't see when it breaks. What version of Jupyter Lab are you on?

**Comment by PhilippRisius** [comment]
I'm on jupyterlab version 4.2.5.

**Comment by jmshea** [comment]
Interesting. It still works fine on 4.2.4. I will upgrade in a venv and see what I can do to fix it.

**Comment by jmshea** [comment]
OK. This is regression with 4.2.5 and later. I can provide a simpler workaround, but I created an issue on the Jupyter Lab repo, and we will see what they say. I can't make the workaround tonight, but I should be able to do it in a few days at the latest.
