### ISSUE TITLE
Preserve_Quizzes_with_Student_Answers

### ISSUE THREAD

**Issue by austinpollok** [jmshea/jupyterquiz#5]
For some homework assignments, I ask multiple choice questions (without any feedback and I set all answers as true) inside a Jupyter Notebook with the intent of grading the students' response when they submit their notebooks. However, when I open a notebook, the quiz resets and I can't see the output like I would from any other code cell.

**Comment by jmshea** [comment]
I believe that I have implemented the functionality that you requested, as best as I can within the restrictions that JupyterLab puts on the exchange of information from JavaScript back to the notebook. Please see the link below for details and add any feedback here.

https://github.com/jmshea/jupyterquiz#preserving-student-responses
