### ISSUE TITLE
the default answer

### ISSUE THREAD

**Issue by egy1st** [jmshea/jupyterquiz#7]
First, I would like to thank you for such a great tool.

Since you randomize answers and this is always welcome, I think there is no need to set a number to correct answer. You can always set it to the first one.

Also, I wonder how can I include an image in my question or its answers

Thanks in advance
Mohamed Ali

**Comment by jmshea** [comment]
Thanks for your feedback.

1) The idea of not marking an answer as the correct one could simplify the JSON a little bit, but I prefer to keep that for flexibility and clarity. This flexibility also allows the possibility of having questions with multiple correct answers.
2) You can actually include any HTML you like in the questions or answers. So, you should be able to insert an image in your question like: <img src=\"http://mydomain/myimage.json\" width=200> (where I am showing that you need to escape the quotation marks in your JSON file.
